### ISSUE TITLE
把现有 issue 采集为本地 Markdown 文件

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/kup#8]
增加 `-d` `--dump` 布尔值选项，如果有，则进行反向操作（不是发布，而是采集）。

获取 repo 和 id 参数的逻辑不变。

此时如果不指定文件，则自动在当前目录生成一个文件，命名为 `{repo-owner}--{repo-name}--{id}.md`。采集成功后写入 YAML 元数据。

**Comment by cssmagic** [comment]
Prompts to Codex:

> 接下来有一个新需求：把现有 issue 采集为本地 Markdown 文件。
>
> 具体构思如下，请帮我思考完善：
> * 增加 `-d` `--dump` 布尔值选项，如果有，则进行反向操作（不是发布，而是采集）。
> * 获取 repo 和 id 参数的逻辑不变。
> * 此时如果不指定文件，则自动在当前目录生成一个文件，命名为 `{id}.md`。采集成功后写入元数据。元数据各个字段的处理如下：
> 	* `repo`：跟现有写回元数据的逻辑一致——只有当 repo 是通过 CLI 指定时才写回。
> 	* `id`：总是写回。
> 	* `tags`：解析 GitHub 返回的 issue 数据，把 label 信息写入此字段。写入格式为 `[label1, label2]`。如果该 issue 没有 label，则无需写此字段。
> 	* `title`：总是写回。

……

> 好的，我基本同意。几点反馈如下：
> * 如果目标文件已存在，则在写文件之前提示用户确认。
> * 关于 `tags` 元数据的语法，请帮我分析 YAML 库的选项，把数组尽可能写成单行模式。
> * `meta.js` 手工生成元数据的方式是为了最小化修改现有元数据。为提高可靠性，可以优化这部分代码，比如把用户数据包一层引号或做转义。
>
> 请确认这些细节是否可行。

……

> 好的，我接受。请开始实现。

……

> 我发现了一个问题。当我在命令行中指定 dump 目标文件时，如果文件内容为空的话，会抛错：
>
> ```
> TypeError: Cannot read properties of undefined (reading 'trimEnd')
>   at _detectMetaSectionLineQty (file:///Users/cssmagic/gh/kup/lib/parse.js:43:52)
>   at parse (file:///Users/cssmagic/gh/kup/lib/parse.js:19:22)
>   at getFileInfoForMode (file:///Users/cssmagic/gh/kup/lib/main.js:111:9)
>   at async main (file:///Users/cssmagic/gh/kup/lib/main.js:22:19)
> ```

……

> 我顺便问一下，为什么在 dump 模式下需要解析目标文件的内容？是为了解析出 repo 和 id 吗？

……


> 是的，我希望是后一种逻辑。

……


> dump 模式覆盖本地文件之前向用户确认时，回车的默认选项改为 Yes。

……


> 我有一个点想要优化一下。在如下的命令行交互日志中，URL 那一行出现在 dump 成功之后。我希望 URL 这一行出现在 `[Kup] Dumping ...` 这一行之后，并且把 `[Success]` 字样替换为 `Dumping`。
>
> ```
> $ kup -d --id 10
> [Kup] Dumping "cssmagic/kup-demo#10"...
> ✔ Kup is going to overwrite the local file "/Users/cssmagic/gh/kup-demo/test/stuff/dump/10.md", OK? Yes
> [Kup] [Success] Dumped "cssmagic/kup-demo#10" to "/Users/cssmagic/gh/kup-demo/test/stuff/dump/10.md"!
> [Kup] [Success] URL: https://github.com/cssmagic/kup-demo/issues/10
> [Kup] Done!
> ```

……

**Comment by cssmagic** [comment]
> 接下来我们来更新 README。先更新 `README.zh.md`（中文版）。只需把采集用法和 -d 参数加进去就行了。

……

> 很好。我稍微修改了一下中文版。接下来请参考中文版更新的内容，同步修改 `README.md`（英文版）。

……
